apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentname }}
  ports:
    - port: {{ .Values.serviceport | int }}
      targetPort: {{ .Values.containerport | int }}
      nodePort: {{ .Values.nodeport | int }}
      protocol: TCP
