apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentname }}
  ports:
    - nodePort: {{ .Values.nodeport }}
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.containerport }}
      protocol: TCP