apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentname }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.containerport | int }}
      protocol: TCP
      {{- if .Values.nodeport }}
      nodePort: {{ .Values.service.nodeport | int }}
      {{- end }}