apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentname }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerport }}
      nodePort: {{ .Values.nodeport }}
      protocol: TCP
